/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <gdk/gdkdisplay.h> header file. */
#define HAVE_GDK_GDKDISPLAY_H 1

/* Define to 1 if you have the <gdk/gdkscreen.h> header file. */
#define HAVE_GDK_GDKSCREEN_H 1

/* Define to 1 if you have the `gdk_x11_colormap_foreign_new' function. */
#define HAVE_GDK_X11_COLORMAP_FOREIGN_NEW 1

/* Define to 1 if the system has the type `GLhalfNV'. */
#define HAVE_GLHALFNV 1

/* Define to 1 if the system has the type `GLXFBConfigIDSGIX'. */
#define HAVE_GLXFBCONFIGIDSGIX 1

/* Define to 1 if the system has the type `GLXFBConfigSGIX'. */
#define HAVE_GLXFBCONFIGSGIX 1

/* Define to 1 if the system has the type `GLXPbufferSGIX'. */
#define HAVE_GLXPBUFFERSGIX 1

/* Define to 1 if the system has the type `GLXVideoSourceSGIX'. */
#define HAVE_GLXVIDEOSOURCESGIX 1

/* Define to 1 if you have the <GL/glu.h> header file. */
#define HAVE_GL_GLU_H 1

/* Define to 1 if you have the <GL/glx.h> header file. */
#define HAVE_GL_GLX_H 1

/* Define to 1 if you have the <GL/gl.h> header file. */
#define HAVE_GL_GL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `Xmu' library (-lXmu). */
#define HAVE_LIBXMU 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `sqrt' function. */
#define HAVE_SQRT 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <X11/Xmu/StdCmap.h> header file. */
#define HAVE_X11_XMU_STDCMAP_H 1

/* Define to 1 if you have the <Xmu/StdCmap.h> header file. */
/* #undef HAVE_XMU_STDCMAP_H */

/* Define to 1 if the system has the type `__GLXextFuncPtr'. */
#define HAVE___GLXEXTFUNCPTR 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "gtkglext-list@gnome.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "gtkglext"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "gtkglext 1.2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "gtkglext"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2.0"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */
