#!/bin/bash

# check root
if [[ $UID -ne 0 ]]; then 
    echo "This script must be run as root"
    exit 1
fi

# install WrapReader
g++ wrap920ARdecode.cpp -lrt -o wrap920ARdecode && echo "Compiled wrap920ARdecode" &&
cp -f wrap920ARdecode /usr/local/bin/ && cp -f wrap920ARdecode /usr/local/bin/ &&
echo "Installed wrap920ARdecode" &&

# install udev rule
cp -f wrap920AR.rules /etc/udev/rules.d/ && service udev restart && echo "Installed wrap920AR.rules" &&

# done
echo "Done"
