/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Use the Apple OpenGL framework. */
/* #undef HAVE_APPLE_OPENGL_FRAMEWORK */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have POSIX threads libraries and header files. */
#define HAVE_PTHREAD 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Defined if support for rendering JPEG textures is enabled. */
#define OPENVRML_ENABLE_JPEG_TEXTURES 1

/* Defined if support for rendering PNG textures is enabled. */
#define OPENVRML_ENABLE_PNG_TEXTURES 1

/* Defined if support for rendering Text nodes is enabled. */
#define OPENVRML_ENABLE_RENDER_TEXT_NODE 1

/* Defined if Script node Java support is enabled. */
/* #undef OPENVRML_ENABLE_SCRIPT_NODE_JAVA */

/* Defined if Script node JavaScript support is enabled. */
#define OPENVRML_ENABLE_SCRIPT_NODE_JAVASCRIPT 1

/* const for FreeType callback function signatures. */
#define OPENVRML_FT_CONST const

/* Name of package */
#define PACKAGE "openvrml"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "openvrml-develop@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "OpenVRML"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "OpenVRML 0.16.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "openvrml"

/* Define to the home page for this package. */
/* #undef PACKAGE_URL */

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.16.2"

/* Define to necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.16.2"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */
